"""domain-service (Python, API-key mode) — a standalone product service.

The domain-service extension model from Python *without* importing framework
internals: this service runs in its own process/deployment and delegates
tenancy decisions to the Synapse API server-to-server with an org API key —
the same pattern as the Go/Java variants. (For the in-process extension
model, see examples/python/hello-saas.)

Per request it:
  1. authenticates the caller with its own bearer token
  2. checks the org's entitlement (feature gate) via the SDK
  3. meters the work atomically (402 typed error when ai_tokens trips)
  4. does the domain work

Env:
    SYNAPSE_API    framework API (default http://localhost:8000)
    SYNAPSE_KEY    org API key (console → API keys) — the service's credential
    SERVICE_TOKEN  token your product's clients present (default "demo-token")
"""

from __future__ import annotations

import json
import os
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from synapse_saas_client import SynapseClient, SynapseLimitError

API = os.environ.get("SYNAPSE_API", "http://localhost:8000")
KEY = os.environ.get("SYNAPSE_KEY", "")
SERVICE_TOKEN = os.environ.get("SERVICE_TOKEN", "demo-token")
PORT = int(os.environ.get("ADDR_PORT", "8092"))

if not KEY:
    sys.exit("Set SYNAPSE_KEY to an org API key (console → API keys)")

client = SynapseClient(API, api_key=KEY)


def estimate_tokens(prompt: str) -> int:
    """Stand-in for what a real model reports; meters actual consumption."""
    return 500 + 25 * len(prompt)


class Handler(BaseHTTPRequestHandler):
    def _json(self, status: int, body: dict) -> None:
        payload = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def _authorized(self) -> bool:
        return self.headers.get("Authorization") == f"Bearer {SERVICE_TOKEN}"

    def do_GET(self) -> None:  # noqa: N802 — http.server API
        if self.path != "/v1/plan":
            self._json(404, {"error": "not found"})
            return
        if not self._authorized():
            self._json(401, {"error": "unauthorized"})
            return
        ent = client.entitlements.effective()
        self._json(200, {"plan": ent["plan_key"], "features": ent["features"], "limits": ent["limits"]})

    def do_POST(self) -> None:  # noqa: N802 — http.server API
        if self.path != "/v1/reports":
            self._json(404, {"error": "not found"})
            return
        if not self._authorized():
            self._json(401, {"error": "unauthorized"})
            return

        length = int(self.headers.get("Content-Length", 0))
        try:
            body = json.loads(self.rfile.read(length))
            prompt = str(body.get("prompt", ""))
        except (json.JSONDecodeError, ValueError):
            prompt = ""
        if not prompt:
            self._json(400, {"error": "prompt required"})
            return

        # 1 — Feature gate
        ent = client.entitlements.effective()
        if "advanced_reports" not in ent["features"]:
            self._json(
                403,
                {
                    "error": "feature_not_entitled",
                    "feature": "advanced_reports",
                    "current_plan": ent["plan_key"],
                },
            )
            return

        # 2 — Meter before the work
        tokens = estimate_tokens(prompt)
        try:
            client.usage.consume("ai_tokens", tokens)
        except SynapseLimitError as err:
            self._json(
                402,
                {
                    "error": "usage_limit_exceeded",
                    "metric": err.metric,
                    "limit": err.limit,
                    "upgrade_url": err.body.get("upgrade_url"),
                },
            )
            return

        # 3 — Domain work
        self._json(
            200,
            {
                "report": f'Report for "{prompt}" — generated by the Python domain service.',
                "tokens_used": tokens,
                "plan": ent["plan_key"],
                "metered": True,
            },
        )


if __name__ == "__main__":
    print(f"Python domain service on :{PORT} — POST /v1/reports, GET /v1/plan")
    ThreadingHTTPServer(("", PORT), Handler).serve_forever()
