/**
 * domain-service (TypeScript) — a real product service extending the framework.
 *
 * The polyglot extension model: this Node service owns its domain
 * (POST /v1/reports) and delegates tenancy decisions to the Synapse API
 * server-to-server with an org API key. Same pattern as the Go/Java variants.
 *
 *   SYNAPSE_API   framework API (default http://localhost:8000)
 *   SYNAPSE_KEY   org API key (console → API keys)
 *   SERVICE_TOKEN token your product's clients present (default "demo-token")
 */
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";

import {
  SynapseClient,
  SynapseFeatureGatedError,
  SynapseLimitError,
} from "@synapse-saas/client";

const api = process.env.SYNAPSE_API ?? "http://localhost:8000";
const key = process.env.SYNAPSE_KEY;
const serviceToken = process.env.SERVICE_TOKEN ?? "demo-token";
const port = Number(process.env.ADDR_PORT ?? 8093);

if (!key) {
  console.error("Set SYNAPSE_KEY to an org API key (console → API keys)");
  process.exit(1);
}

// One shared SDK client: the org's credential, pinned server-side.
const client = new SynapseClient(api, { apiKey: key });

/** Stand-in for what a real model reports; meters actual consumption. */
function estimateTokens(prompt: string): number {
  return 500 + 25 * prompt.length;
}

function json(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  res.writeHead(status, { "Content-Type": "application/json", "Content-Length": payload.length });
  res.end(payload);
}

function authorized(req: IncomingMessage): boolean {
  return req.headers.authorization === `Bearer ${serviceToken}`;
}

async function readBody(req: IncomingMessage): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of req) {
    chunks.push(chunk as Buffer);
  }
  return Buffer.concat(chunks).toString("utf8");
}

const server = createServer(async (req, res) => {
  const url = req.url ?? "";

  // ── Product metadata: what the org can see ──────────────────────────────
  if (req.method === "GET" && url === "/v1/plan") {
    if (!authorized(req)) {
      json(res, 401, { error: "unauthorized" });
      return;
    }
    const ent = (await client.entitlements.effective()) as Record<string, unknown>;
    json(res, 200, { plan: ent.plan_key, features: ent.features, limits: ent.limits });
    return;
  }

  // ── The domain endpoint: gated + metered report generation ──────────────
  if (req.method === "POST" && url === "/v1/reports") {
    if (!authorized(req)) {
      json(res, 401, { error: "unauthorized" });
      return;
    }
    let prompt = "";
    try {
      prompt = String((JSON.parse(await readBody(req)) as { prompt?: string }).prompt ?? "");
    } catch {
      prompt = "";
    }
    if (!prompt) {
      json(res, 400, { error: "prompt required" });
      return;
    }

    // 1 — Feature gate
    const ent = (await client.entitlements.effective()) as {
      plan_key: string;
      features: string[];
    };
    if (!ent.features.includes("advanced_reports")) {
      json(res, 403, {
        error: "feature_not_entitled",
        feature: "advanced_reports",
        current_plan: ent.plan_key,
      });
      return;
    }

    // 2 — Meter BEFORE the work: quota trips are typed 402s
    const tokens = estimateTokens(prompt);
    try {
      await client.usage.consume("ai_tokens", tokens);
    } catch (err) {
      if (err instanceof SynapseLimitError) {
        json(res, 402, {
          error: "usage_limit_exceeded",
          metric: err.metric,
          limit: err.limit,
          upgrade_url: (err.body as { upgrade_url?: string }).upgrade_url,
        });
        return;
      }
      throw err;
    }

    // 3 — Domain work
    json(res, 200, {
      report: `Report for "${prompt}" — generated by the TypeScript domain service.`,
      tokens_used: tokens,
      plan: ent.plan_key,
      metered: true,
    });
    return;
  }

  json(res, 404, { error: "not found" });
});

server.listen(port, () => {
  console.log(`TypeScript domain service on :${port} — POST /v1/reports, GET /v1/plan`);
});
