// domain-service (Go) — a real product service extending the framework.
//
// This is the polyglot extension model: your Go service owns its domain
// (here: report generation) and delegates tenancy decisions to the Synapse
// API server-to-server with an org API key.
//
// Per request it:
//  1. authenticates the caller with its own bearer token (any mechanism —
//     in a real product this is your user/session layer or a forwarded JWT)
//  2. checks the org's entitlement (feature gate) via the SDK
//  3. meters the work atomically (usage.consume → 402 typed error when the
//     org's ai_tokens quota trips — before the expensive work runs)
//  4. does the domain work and returns it
//
// Env:
//
//	SYNAPSE_API   framework API (default http://localhost:8000)
//	SYNAPSE_KEY   org API key (console → API keys) — the service's credential
//	SERVICE_TOKEN token your product's clients present (default "demo-token")
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/allandanos/synapse-saas/sdk/go"
)

type reportRequest struct {
	Prompt string `json:"prompt"`
}

type reportResponse struct {
	Report   string `json:"report"`
	Tokens   int    `json:"tokens_used"`
	Plan     string `json:"plan"`
	Metered  bool   `json:"metered"`
}

// estimates tokens for the demo "model"; a real service meters what the
// model actually consumed.
func estimateTokens(prompt string) int { return 500 + 25*len(prompt) }

func main() {
	api := envOr("SYNAPSE_API", "http://localhost:8000")
	key := os.Getenv("SYNAPSE_KEY")
	serviceToken := envOr("SERVICE_TOKEN", "demo-token")

	if key == "" {
		log.Fatal("Set SYNAPSE_KEY to an org API key (console → API keys)")
	}

	// One shared SDK client: the org's credential, pinned server-side.
	client, err := synapse.New(api, synapse.Options{APIKey: key})
	if err != nil {
		log.Fatal(err)
	}

	mux := http.NewServeMux()

	// ── Product metadata: what the org can see ────────────────────────────
	mux.HandleFunc("GET /v1/plan", func(w http.ResponseWriter, r *http.Request) {
		if !authorized(r, serviceToken) {
			unauthorized(w)
			return
		}
		ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
		defer cancel()

		ent, err := client.Entitlements().Effective(ctx)
		if err != nil {
			upstream(w, err)
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{
			"plan":     ent["plan_key"],
			"features": ent["features"],
			"limits":   ent["limits"],
		})
	})

	// ── The domain endpoint: gated + metered report generation ────────────
	mux.HandleFunc("POST /v1/reports", func(w http.ResponseWriter, r *http.Request) {
		if !authorized(r, serviceToken) {
			unauthorized(w)
			return
		}
		var req reportRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.Prompt == "" {
			writeJSON(w, http.StatusBadRequest, map[string]string{"error": "prompt required"})
			return
		}
		ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
		defer cancel()

		// 1 — Feature gate: is the org entitled to advanced_reports?
		ent, err := client.Entitlements().Effective(ctx)
		if err != nil {
			upstream(w, err)
			return
		}
		features, _ := ent["features"].([]any)
		entitled := false
		for _, f := range features {
			if f == "advanced_reports" {
				entitled = true
			}
		}
		if !entitled {
			writeJSON(w, http.StatusForbidden, map[string]any{
				"error":        "feature_not_entitled",
				"feature":      "advanced_reports",
				"current_plan": ent["plan_key"],
			})
			return
		}

		// 2 — Meter BEFORE the work: quota trips return a typed error.
		tokens := estimateTokens(req.Prompt)
		if _, err := client.Usage().Consume(ctx, "ai_tokens", tokens); err != nil {
			var limitErr *synapse.LimitError
			if errors.As(err, &limitErr) {
				writeJSON(w, http.StatusPaymentRequired, map[string]any{
					"error":        "usage_limit_exceeded",
					"metric":       limitErr.Metric(),
					"limit":        limitErr.Body["limit"],
					"upgrade_url":  limitErr.Body["upgrade_url"],
				})
				return
			}
			upstream(w, err)
			return
		}

		// 3 — The domain work (stand-in for calling your model).
		report := fmt.Sprintf("Report for %q — generated by the Go domain service.", req.Prompt)

		writeJSON(w, http.StatusOK, reportResponse{
			Report:  report,
			Tokens:  tokens,
			Plan:    fmt.Sprint(ent["plan_key"]),
			Metered: true,
		})
	})

	addr := envOr("ADDR", ":8090")
	fmt.Printf("Go domain service on %s — POST /v1/reports, GET /v1/plan\n", addr)
	log.Fatal(http.ListenAndServe(addr, mux))
}

func authorized(r *http.Request, token string) bool {
	auth := r.Header.Get("Authorization")
	return auth == "Bearer "+token
}

func unauthorized(w http.ResponseWriter) {
	writeJSON(w, http.StatusUnauthorized, map[string]string{"error": "unauthorized"})
}

func upstream(w http.ResponseWriter, err error) {
	writeJSON(w, http.StatusBadGateway, map[string]string{"error": "framework unavailable", "detail": err.Error()})
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
