"""Invoicing engine: draft-from-usage → finalize → pay.

Closes the self-contained invoicing gap: orgs on the Manual provider (or
enterprise contracts) get real invoices generated by the framework — not
just event ledgers from payment providers.

Lifecycle (state-checked):
    draft → open (finalize: assigns a number, locks the amounts)
    open   → paid (payment recorded)
    draft  → void
    open   → void (rare — uncollectible is the usual terminal for bad debt)

Line items live in `invoice_lines`: plan charge + metered overage lines,
both computed from the org's subscription snapshot and usage counters at
draft time. Provider-sourced invoices (webhook upserts) never create lines —
their shape is the provider's; ours is ours.
"""

from __future__ import annotations

from datetime import UTC, date, datetime, timedelta
from decimal import ROUND_HALF_UP, Decimal
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import BigInteger, CheckConstraint, ForeignKey, String, Text, func, select
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Mapped, mapped_column

from synapse_saas.audit.service import AuditService
from synapse_saas.billing.models import Invoice
from synapse_saas.core import events
from synapse_saas.core.db import Base, TimestampMixin
from synapse_saas.core.errors import InvoiceNotFoundError, ValidationFailedError
from synapse_saas.core.logging import get_logger
from synapse_saas.core.outbox import append_outbox
from synapse_saas.subscriptions.models import Subscription
from synapse_saas.subscriptions.state_machine import OCCUPYING_STATUSES
from synapse_saas.usage.models import UsageCounter

logger = get_logger(__name__)

# ₱0.20 per 1,000 units — the prompt §5 example rate. Extension point:
# per-metric rates via plan metadata; single default keeps v1 honest.
OVERAGE_PHP_PER_1K = 20
OVERAGE_METRICS = ("ai_tokens", "ai_requests")

INVOICE_TRANSITIONS: dict[str, frozenset[str]] = {
    "draft": frozenset({"open", "void"}),
    "open": frozenset({"paid", "void", "uncollectible"}),
    "paid": frozenset(),
    "void": frozenset(),
    "uncollectible": frozenset(),
}


class InvoiceLine(Base, TimestampMixin):
    """A single billable line on a framework-generated invoice."""

    __tablename__ = "invoice_lines"
    __table_args__ = (
        CheckConstraint(
            "kind IN ('plan','overage','credit','custom')",
            name="ck_invoice_lines_kind",
        ),
    )

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    invoice_id: Mapped[UUID] = mapped_column(
        ForeignKey("invoices.id", ondelete="CASCADE"), index=True, nullable=False
    )
    kind: Mapped[str] = mapped_column(String(16), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    quantity: Mapped[int] = mapped_column(BigInteger, default=1, nullable=False)
    unit_amount_cents: Mapped[int] = mapped_column(BigInteger, nullable=False)
    amount_cents: Mapped[int] = mapped_column(BigInteger, nullable=False)
    # Overage lines: the metric and the included/exceeded split
    metric: Mapped[str | None] = mapped_column(String(100))
    properties: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict, nullable=False)


def _assert_invoice_transition(current: str, target: str) -> None:
    if current == target:
        return
    if target not in INVOICE_TRANSITIONS.get(current, frozenset()):
        allowed = sorted(INVOICE_TRANSITIONS.get(current, frozenset()))
        raise ValidationFailedError(
            f"Cannot move invoice from {current!r} to {target!r}",
            extras={"from": current, "to": target, "allowed": allowed},
        )


class InvoicingService:
    """Framework-native invoice generation and payment recording."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    # ── Draft: build lines from the org's plan + usage ───────────────────────

    async def draft_for_org(
        self,
        organization_id: UUID,
        *,
        period: date | None = None,
        created_by_user_id: UUID | None = None,
    ) -> Invoice:
        """Create (or return the existing) draft invoice for the period.

        Idempotent per (org, period): an existing draft is returned unchanged
        so re-running a billing job is safe.
        """
        period_start = period or _month_bucket()
        existing = await self._find_draft(organization_id, period_start)
        if existing is not None:
            return existing

        sub = await self._active_subscription(organization_id)
        lines: list[dict[str, Any]] = []

        # 1 — Plan charge line (from the purchase-time snapshot: grandfathering)
        snapshot = sub.plan_snapshot or {}
        plan_key = str(snapshot.get("key", "unknown"))
        plan_cents = int(snapshot.get("price_cents") or 0)
        if plan_cents > 0:
            lines.append(
                {
                    "kind": "plan",
                    "description": (
                        f"{snapshot.get('name', plan_key)} plan ({snapshot.get('interval', 'month')}ly)"
                    ),
                    "quantity": 1,
                    "unit_amount_cents": plan_cents,
                    "amount_cents": plan_cents,
                }
            )

        # 2 — Overage lines: usage beyond each metric's included amount
        for metric in OVERAGE_METRICS:
            overage = await self._overage_cents(organization_id, metric, period_start)
            if overage[0] > 0:
                units, cents = overage
                lines.append(
                    {
                        "kind": "overage",
                        "description": f"{metric} overage — {units:,} units over plan",
                        "quantity": units,
                        "unit_amount_cents": _per_unit_cents(),
                        "amount_cents": cents,
                        "metric": metric,
                    }
                )

        subtotal = sum(line["amount_cents"] for line in lines)
        invoice = Invoice(
            organization_id=organization_id,
            provider="synapse",
            currency=str(snapshot.get("currency", "PHP")),
            subtotal_cents=subtotal,
            total_cents=subtotal,
            status="draft",
            period_start=datetime.combine(period_start, datetime.min.time(), tzinfo=UTC),
            period_end=datetime.combine(
                period_start + timedelta(days=32), datetime.min.time(), tzinfo=UTC
            ).replace(day=1)
            - timedelta(days=1),
        )
        if invoice.period_end is not None:
            invoice.period_end = invoice.period_end.replace(hour=23, minute=59, second=59)
        self.session.add(invoice)
        await self.session.flush()

        for line in lines:
            self.session.add(InvoiceLine(invoice_id=invoice.id, **line))
        await self.session.flush()

        AuditService(self.session).log(
            events.INVOICE_CREATED,
            organization_id=organization_id,
            target_type="invoice",
            target_id=invoice.id,
            diff={"period": period_start.isoformat(), "lines": len(lines), "subtotal_cents": subtotal},
        )
        logger.info("invoice_drafted", org=str(organization_id), period=str(period_start), lines=len(lines))
        return invoice

    # ── Finalize: number it, open it ─────────────────────────────────────────

    async def finalize(self, invoice_id: UUID, organization_id: UUID) -> Invoice:
        invoice = await self._get_scoped(invoice_id, organization_id)
        _assert_invoice_transition(invoice.status, "open")
        invoice.status = "open"
        invoice.number = await self._next_number(organization_id)
        invoice.issued_at = datetime.now(UTC)
        await self.session.flush()

        append_outbox(
            self.session,
            event_type=events.INVOICE_CREATED,
            aggregate_type="invoice",
            aggregate_id=invoice.id,
            organization_id=organization_id,
            payload={"number": invoice.number, "total_cents": invoice.total_cents, "status": "open"},
        )
        # Delivery email rides the same outbox (worker renders + attaches the PDF)
        append_outbox(
            self.session,
            event_type="invoice.email",
            aggregate_type="invoice",
            aggregate_id=invoice.id,
            organization_id=organization_id,
            payload={"invoice_id": str(invoice.id), "reason": "finalized"},
        )
        AuditService(self.session).log(
            "invoice.finalized",
            organization_id=organization_id,
            target_type="invoice",
            target_id=invoice.id,
            diff={"number": invoice.number},
        )
        return invoice

    # ── Record a payment ───────────────────────────────────────────────────────

    async def record_payment(
        self,
        invoice_id: UUID,
        organization_id: UUID,
        *,
        amount_cents: int,
        reference: str | None = None,
    ) -> Invoice:
        invoice = await self._get_scoped(invoice_id, organization_id)
        _assert_invoice_transition(invoice.status, "paid")
        if amount_cents < invoice.total_cents:
            raise ValidationFailedError(
                "Partial payments are not supported in v1",
                extras={"expected": invoice.total_cents, "received": amount_cents},
            )
        invoice.status = "paid"
        invoice.paid_at = datetime.now(UTC)
        await self.session.flush()

        append_outbox(
            self.session,
            event_type=events.INVOICE_PAID,
            aggregate_type="invoice",
            aggregate_id=invoice.id,
            organization_id=organization_id,
            payload={
                "total_cents": invoice.total_cents,
                "currency": invoice.currency,
                "reference": reference,
            },
        )
        append_outbox(
            self.session,
            event_type="invoice.email",
            aggregate_type="invoice",
            aggregate_id=invoice.id,
            organization_id=organization_id,
            payload={"invoice_id": str(invoice.id), "reason": "paid"},
        )
        AuditService(self.session).log(
            "invoice.payment_recorded",
            organization_id=organization_id,
            target_type="invoice",
            target_id=invoice.id,
            diff={"amount_cents": amount_cents, "reference": reference},
        )
        return invoice

    async def void(self, invoice_id: UUID, organization_id: UUID) -> Invoice:
        invoice = await self._get_scoped(invoice_id, organization_id)
        _assert_invoice_transition(invoice.status, "void")
        invoice.status = "void"
        await self.session.flush()
        AuditService(self.session).log(
            "invoice.voided",
            organization_id=organization_id,
            target_type="invoice",
            target_id=invoice.id,
        )
        return invoice

    # ── Queries ────────────────────────────────────────────────────────────────

    async def get(self, invoice_id: UUID, organization_id: UUID) -> Invoice:
        return await self._get_scoped(invoice_id, organization_id)

    async def lines_for(self, invoice_id: UUID, organization_id: UUID) -> list[InvoiceLine]:
        invoice = await self._get_scoped(invoice_id, organization_id)
        rows = await self.session.execute(select(InvoiceLine).where(InvoiceLine.invoice_id == invoice.id))
        return list(rows.scalars().all())

    # ── Internals ──────────────────────────────────────────────────────────────

    async def _get_scoped(self, invoice_id: UUID, organization_id: UUID) -> Invoice:
        invoice = await self.session.get(Invoice, invoice_id)
        if invoice is None or invoice.organization_id != organization_id:
            raise InvoiceNotFoundError("Invoice not found")  # cross-tenant 404
        return invoice

    async def _find_draft(self, organization_id: UUID, period_start: date) -> Invoice | None:
        rows = await self.session.execute(
            select(Invoice).where(
                Invoice.organization_id == organization_id,
                Invoice.status == "draft",
                func.date(Invoice.period_start) == period_start,
            )
        )
        return rows.scalar_one_or_none()

    async def _active_subscription(self, organization_id: UUID) -> Subscription:
        sub = (
            await self.session.execute(
                select(Subscription)
                .where(
                    Subscription.organization_id == organization_id,
                    Subscription.status.in_(OCCUPYING_STATUSES),
                )
                .order_by(Subscription.created_at.desc())
                .limit(1)
            )
        ).scalar_one_or_none()
        if sub is None:
            raise ValidationFailedError("Organization has no active subscription to bill")
        return sub

    async def _overage_cents(self, organization_id: UUID, metric: str, period: date) -> tuple[int, int]:
        """(units over the included amount, cents for those units)."""
        used = (
            await self.session.execute(
                select(func.coalesce(func.sum(UsageCounter.quantity_total), 0)).where(
                    UsageCounter.organization_id == organization_id,
                    UsageCounter.metric == metric,
                    UsageCounter.period_start == period,
                )
            )
        ).scalar_one()

        # The included amount comes from the ENTITLEMENTS RESOLVER — not the
        # plan table — so addon grants (limit:<metric>) and overrides shape
        # billing exactly like they shape enforcement. One source of truth.
        from synapse_saas.entitlements.service import EntitlementService

        entitlements = await EntitlementService(self.session).effective_for_org(organization_id)
        resolved_limit = entitlements.limit(metric)
        limit = resolved_limit.value if resolved_limit else None

        if limit is None or used <= limit:
            return 0, 0
        units_over = int(used - limit)
        cents = int(
            (Decimal(units_over) / Decimal(1000) * Decimal(OVERAGE_PHP_PER_1K)).quantize(
                Decimal(1), rounding=ROUND_HALF_UP
            )
        )
        return units_over, cents

    async def _next_number(self, organization_id: UUID) -> str:
        """INV-YYYYMM-#### scoped per org (count of prior finals + 1).

        Not a gapless sequence — gapless legal numbering is a jurisdiction
        concern; this is unique, sortable, and auditable.
        """
        count = (
            await self.session.execute(
                select(func.count())
                .select_from(Invoice)
                .where(
                    Invoice.organization_id == organization_id,
                    Invoice.number.is_not(None),
                )
            )
        ).scalar_one()
        stamp = datetime.now(UTC).strftime("%Y%m")
        return f"INV-{stamp}-{count + 1:04d}"


def _month_bucket(now: datetime | None = None) -> date:
    return (now or datetime.now(UTC)).date().replace(day=1)


def _per_unit_cents() -> int:
    """Minor units per single unit — stored per line for auditability."""
    return OVERAGE_PHP_PER_1K  # per 1k; per-unit price shown as the 1k rate
