"""Framework-default invoice PDF rendering.

Self-contained: fpdf2 (pure Python — no wkhtmltopdf, no headless Chrome, no
system deps), Helvetica core fonts (no embedding licensing). Deterministic
output for a given invoice so PDFs are reproducible byte-for-byte except
for fpdf2's file-ID header.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from fpdf import FPDF
from fpdf.enums import XPos, YPos

if TYPE_CHECKING:
    from synapse_saas.billing.invoicing import InvoiceLine
    from synapse_saas.billing.models import Invoice

# A4 portrait, mm
PAGE_W = 210
PAGE_H = 297
MARGIN = 18

INK = (24, 24, 27)  # zinc-900
MUTED = (113, 113, 122)  # zinc-500
HAIRLINE = (228, 228, 231)  # zinc-200
BRAND = (24, 24, 27)

SYMBOLS = {"PHP": "PHP ", "USD": "USD ", "EUR": "EUR "}


def _latin1(text: str) -> str:
    """Core-font PDFs are latin-1; map or drop anything outside it."""
    replacements = {
        "\u2014": "-",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2022": "*",
        "\u20b1": "PHP ",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", "replace").decode("latin-1")


def format_money(cents: int, currency: str) -> str:
    major = cents / 100
    text = f"{major:,.2f}"
    return f"{SYMBOLS.get(currency, currency + ' ')}{text}"


def format_qty(n: int) -> str:
    return f"{n:,}"


def _cell_sanitize(fn: Any, *args: Any, **kwargs: Any) -> Any:
    """Sanitize the `text` argument of fpdf2 cell/multi_cell calls.

    `text` is positional #3 (w, h, text) in both signatures; it may also
    arrive by keyword. Everything else passes through untouched.
    """
    if "text" in kwargs:
        if isinstance(kwargs["text"], str):
            kwargs["text"] = _latin1(kwargs["text"])
    elif len(args) >= 3 and isinstance(args[2], str):
        args = (*args[:2], _latin1(args[2]), *args[3:])
    return fn(*args, **kwargs)


class InvoicePDF(FPDF):
    """Minimal A4 invoice layout with a repeating footer.

    Every text primitive is sanitized at this boundary — core fonts are
    latin-1, and callers (including future literals) must not have to know
    that. A raw em-dash in a bold cell crashes fpdf2 otherwise.
    """

    def __init__(self, invoice_number: str) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self._invoice_number = invoice_number
        self.set_margins(MARGIN, MARGIN, MARGIN)
        self.set_auto_page_break(auto=True, margin=24)
        self.set_title(f"Invoice {invoice_number}")
        self.add_page()

    def cell(self, *args: Any, **kwargs: Any) -> Any:
        return _cell_sanitize(super().cell, *args, **kwargs)

    def multi_cell(self, *args: Any, **kwargs: Any) -> Any:
        return _cell_sanitize(super().multi_cell, *args, **kwargs)

    def footer(self) -> None:
        self.set_y(-16)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 6, f"Invoice {self._invoice_number} - page {self.page_no()}/{{nb}}", align="C")


def render_invoice_pdf(
    invoice: Invoice,
    lines: list[InvoiceLine],
    *,
    org_name: str,
    billing_email: str | None,
    pay_to_instructions: str | None = None,
) -> bytes:
    """Build the invoice PDF and return its bytes."""
    pdf = InvoicePDF(invoice.number or str(invoice.id))
    _header(pdf, org_name, invoice)
    _bill_to(pdf, org_name, billing_email)
    _meta(pdf, invoice)
    y = _table(pdf, lines, invoice.currency)
    _totals(pdf, y, invoice)
    _instructions(pdf, invoice, pay_to_instructions)
    return bytes(pdf.output())


def _header(pdf: InvoicePDF, org_name: str, invoice: Invoice) -> None:
    # Wordmark
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(*INK)
    pdf.cell(0, 10, "Synapse", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 5, "Generated by the Synapse SaaS Framework", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(6)

    # INVOICE title + number, right-aligned against a left block
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(*INK)
    pdf.cell(0, 8, f"INVOICE {invoice.number or ''}", align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_line_width(0.4)
    pdf.set_draw_color(*HAIRLINE)
    pdf.line(MARGIN, pdf.get_y() + 2, PAGE_W - MARGIN, pdf.get_y() + 2)
    pdf.ln(8)


def _bill_to(pdf: InvoicePDF, org_name: str, billing_email: str | None) -> None:
    org_name = _latin1(org_name)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(30, 5, "Billed to")
    pdf.set_text_color(*INK)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 5, org_name, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    if billing_email:
        pdf.set_x(MARGIN + 30)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        pdf.cell(0, 5, billing_email, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)


def _meta(pdf: InvoicePDF, invoice: Invoice) -> None:
    pdf.set_font("helvetica", "", 9)
    pairs: list[tuple[str, str]] = []
    if invoice.period_start is not None and invoice.period_end is not None:
        pairs.append(("Period", f"{invoice.period_start:%b %d, %Y} - {invoice.period_end:%b %d, %Y}"))
    if invoice.issued_at is not None:
        pairs.append(("Issued", f"{invoice.issued_at:%b %d, %Y}"))
    pairs.append(("Status", invoice.status.upper()))

    col_w = (PAGE_W - 2 * MARGIN) / len(pairs)
    for label, _value in pairs:
        pdf.set_text_color(*MUTED)
        pdf.cell(col_w, 5, label, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.ln(5)
    for _label, value in pairs:
        pdf.set_text_color(*INK)
        pdf.cell(col_w, 5, value, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.ln(10)


def _table(pdf: InvoicePDF, lines: list[InvoiceLine], currency: str) -> float:
    cols = (78.0, 24.0, 36.0, 36.0)  # desc, qty, unit, amount
    # Header
    pdf.set_fill_color(244, 244, 245)
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(*MUTED)
    for w, label in zip(cols, ("Description", "Qty", "Unit price", "Amount"), strict=True):
        pdf.cell(w, 8, label, border=1, fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.ln(8)

    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*INK)
    if not lines:
        pdf.cell(0, 8, "No billable items this period", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        return pdf.get_y()

    for line in lines:
        # Description cell with metric sub-line for overage rows
        h = 10 if line.metric is None else 13
        pdf.cell(cols[0], h, _latin1(line.description)[:80], border=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
        if line.metric is not None:
            pdf.set_xy(MARGIN + 1, pdf.get_y() + h - 4)
            pdf.set_font("helvetica", "I", 7)
            pdf.set_text_color(*MUTED)
            pdf.cell(0, 4, line.metric, new_x=XPos.LMARGIN, new_y=YPos.TOP)
            pdf.set_xy(MARGIN + cols[0], pdf.get_y() - h + 4)
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(*INK)
        pdf.cell(cols[1], h, format_qty(line.quantity), border=1, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(
            cols[2],
            h,
            format_money(line.unit_amount_cents, currency),
            border=1,
            new_x=XPos.RIGHT,
            new_y=YPos.TOP,
        )
        pdf.cell(
            cols[3],
            h,
            format_money(line.amount_cents, currency),
            border=1,
            new_x=XPos.RIGHT,
            new_y=YPos.TOP,
        )
        pdf.ln(h)
    return pdf.get_y()


def _totals(pdf: InvoicePDF, y: float, invoice: Invoice) -> None:
    pdf.set_y(y + 4)
    pdf.set_x(PAGE_W - MARGIN - 90)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(50, 6, "Subtotal", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_text_color(*INK)
    pdf.cell(
        40,
        6,
        format_money(invoice.subtotal_cents, invoice.currency),
        align="R",
        new_x=XPos.RIGHT,
        new_y=YPos.TOP,
    )
    pdf.ln(6)

    pdf.set_x(PAGE_W - MARGIN - 90)
    pdf.set_text_color(*MUTED)
    pdf.cell(50, 6, "Tax", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.set_text_color(*INK)
    pdf.cell(
        40, 6, format_money(invoice.tax_cents, invoice.currency), align="R", new_x=XPos.RIGHT, new_y=YPos.TOP
    )
    pdf.ln(6)

    pdf.set_x(PAGE_W - MARGIN - 90)
    pdf.set_draw_color(*INK)
    pdf.set_line_width(0.4)
    pdf.line(PAGE_W - MARGIN - 90, pdf.get_y(), PAGE_W - MARGIN, pdf.get_y())
    pdf.ln(2)

    pdf.set_x(PAGE_W - MARGIN - 90)
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(50, 7, "Total due", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(
        40,
        7,
        format_money(invoice.total_cents, invoice.currency),
        align="R",
        new_x=XPos.RIGHT,
        new_y=YPos.TOP,
    )
    pdf.ln(10)


def _instructions(pdf: InvoicePDF, invoice: Invoice, pay_to: str | None) -> None:
    if invoice.status == "paid":
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(*INK)
        pdf.cell(
            0,
            6,
            f"PAID{'' if invoice.paid_at is None else f' - {invoice.paid_at:%b %d, %Y}'}",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
        )
        return
    if not pay_to:
        return
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 5, "Payment instructions", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*INK)
    pdf.multi_cell(0, 5, pay_to, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
