"""Invoice PDF issuer block: branding drives the logo/wordmark, legal name, address, tax id, footer."""

from __future__ import annotations

import io
import re
import uuid
import zlib
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

from synapse_saas.billing.invoice_pdf import render_invoice_pdf
from synapse_saas.branding.loader import get_branding


def _invoice() -> Any:
    return SimpleNamespace(
        id=uuid.uuid4(),
        number="INV-0001",
        currency="PHP",
        period_start=None,
        period_end=None,
        issued_at=datetime(2026, 10, 1, tzinfo=UTC),
        status="open",
        subtotal_cents=49900,
        tax_cents=0,
        total_cents=49900,
        paid_at=None,
    )


def _render(**kwargs: Any) -> bytes:
    return render_invoice_pdf(_invoice(), [], org_name="Customer Org", billing_email=None, **kwargs)


def _content(pdf: bytes) -> str:
    """Every stream, inflated where compressed, as latin-1 text (enough to find `(text) Tj`)."""
    parts = []
    for raw in re.findall(rb"stream\r?\n(.*?)\r?\nendstream", pdf, re.DOTALL):
        try:
            parts.append(zlib.decompress(raw))
        except zlib.error:
            parts.append(raw)
    return b"\n".join([pdf, *parts]).decode("latin-1")


def _png() -> bytes:
    from PIL import Image

    buffer = io.BytesIO()
    Image.new("RGB", (40, 20), (255, 85, 0)).save(buffer, format="PNG")
    return buffer.getvalue()


def test_default_issuer_is_the_packaged_brand() -> None:
    text = _content(_render())
    assert "(Synapse)" in text  # legal name under the logo
    assert "Generated by" not in text  # the framework footer is gone
    assert "INVOICE INV-0001" in text


def test_custom_issuer_block(custom_branding: Callable[..., Path]) -> None:
    custom_branding(
        name="Acme",
        invoice={
            "legal_name": "Acme Widgets Inc.",
            "address_lines": ["1 Example Street", "Makati City 1200"],
            "tax_id": "TIN 000-111-222",
            "footer": "Thank you for your business.",
        },
    )
    text = _content(_render())
    for expected in (
        "Acme Widgets Inc.",
        "1 Example Street",
        "Makati City 1200",
        "Tax ID: TIN 000-111-222",
        "Thank you for your business.",
    ):
        assert f"({expected})" in text, expected
    assert "Synapse" not in text


def test_explicit_branding_argument_wins(custom_branding: Callable[..., Path]) -> None:
    custom_branding(name="Explicit Co", logo=None, favicon=None)
    explicit = get_branding()
    text = _content(_render(branding=explicit))
    assert "(Explicit Co)" in text


def test_png_logo_is_embedded_as_an_image(custom_branding: Callable[..., Path]) -> None:
    custom_branding(invoice={"logo": "invoice.png"}, files={"invoice.png": _png()})
    pdf = _render()
    assert b"/Subtype /Image" in pdf


WORDMARK_FONT = re.compile(r"/F\d+ 18(\.\d+)? Tf")  # the 18pt wordmark; nothing else uses 18pt
# A fill the layout never uses: only the logo can emit it
ORANGE_SVG = (
    b'<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">'
    b'<rect width="32" height="32" fill="#ff5500"/></svg>'
)
ORANGE_FILL = re.compile(r"1(\.0+)? 0\.333\d* 0(\.0+)? rg")


class _RecordingLogger:
    def __init__(self) -> None:
        self.events: list[tuple[str, dict[str, Any]]] = []

    def warning(self, event: str, **kw: Any) -> None:
        self.events.append((event, kw))


def test_svg_logo_renders_as_vector_paths(custom_branding: Callable[..., Path]) -> None:
    path = custom_branding(name="Vector Co")
    (path.parent / "logo.svg").write_bytes(ORANGE_SVG)
    text = _content(_render())
    assert ORANGE_FILL.search(text), "the SVG's fill colour was never drawn"
    assert "(Vector Co)" in text  # legal-name line under the drawn logo
    assert not WORDMARK_FONT.search(text)  # a drawn logo replaces the wordmark


def test_without_logo_the_name_is_a_wordmark(custom_branding: Callable[..., Path]) -> None:
    custom_branding(name="Wordmark Co", logo=None)
    text = _content(_render())
    assert WORDMARK_FONT.search(text)
    assert text.count("(Wordmark Co)") == 1  # wordmark only, no duplicate legal-name line


def test_malformed_svg_falls_back_to_the_wordmark(
    custom_branding: Callable[..., Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    from synapse_saas.billing import invoice_pdf

    recorder = _RecordingLogger()
    monkeypatch.setattr(invoice_pdf, "logger", recorder)
    monkeypatch.setattr(invoice_pdf, "_logo_failures", set())
    path = custom_branding(name="Broken Logo Co")
    (path.parent / "logo.svg").write_bytes(b"<svg this is not xml")

    text = _content(_render())
    assert WORDMARK_FONT.search(text), "fallback must print the wordmark"
    assert "(Broken Logo Co)" in text
    assert [event for event, _ in recorder.events] == ["invoice_logo_render_failed"]

    _render()  # logged once per asset per process, not per invoice
    assert len(recorder.events) == 1
